name: Versionamento Automático

on:
  push:
    branches:
      - main  # Dispara a automação sempre que houver push ou merge na main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permissão obrigatória para a Action criar a Tag e a Release

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Garante que todo o histórico de commits seja baixado para calcular a versão

      - name: Gerar Tag Semântica Automática
        id: tag_version
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Token automático do GitHub
          WITH_V: true                               # Cria a tag com 'v' na frente (ex: v1.0.1)
          DEFAULT_BUMP: patch                        # Se o commit for comum, aumenta o Patch por padrão

      - name: Criar Release no GitHub
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          generate_release_notes: true # Gera automaticamente a lista de mudanças com base nos PRs/commits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}